export default Object.freeze({
    LOGIN:'LOGIN',
    ESTRESSAID: "ESTRESSAID" ,
    BIENVENIDO:"BIENVENIDO",
    CREARCUENTA:"CREARCUENTA",
    CONTACTOSDEAYUDA :'CONTACTOSDEAYUDA',
    GESTIONCUENTA:"GESTIONCUENTA",
    CAMBIOCONTRASEÑA:"CAMBIOCONTRASEÑA",
    CAMBIOCONTRASEÑA1:"CAMBIOCONTRASEÑA1",
    CONTRASEÑAOLVIDADA:'CONTRASEÑAOLVIDADA',
    INGRESACODIGO:'INGRESACODIGO',
    INFORMACION:'INFORMACION',
    BORRARCUENTA:'BORRARCUENTA',
    CONVERSACION:'CONVERSACION', 
    PAYMENT:'PAYMENT' ,
    NUEVACONTRASEÑA:'NUEVACONTRASEÑA'
})